### ISSUE TITLE
Add to the man page or other documentation

### ISSUE THREAD

**Issue by pauloney** [borisveytsman/crossrefware#15]
It would be nice to add text like this to the "description" or man page, so one can get a bird eye view of how the files are processed.

1- Each BibTeX record in the file is parsed by BibTeX::Parser, and only the ones that do NOT have the particular record (mrnumber, zblnumber or doi) are processed.

2- The entries that are processed are reported on standar output.

3- The entries processed by BibTeX::Parser are written back by the same suite and are reformated with lines indented by 4 spaces and entry-type uppercased. Example:

````
@BOOK{Cajori:69,
    address = {New York},
    author = {Cajori, F.},
    langid = {english},
    note = {Previously published by The Macmillan Co. in 1904},
    publisher = {Dover},
    title = {An Introduction to the Theory of Equations},
    url = {https://archive.org/details/introductiontoth00cajo/mode/2up},
    year = {1969},
    keywords = {al},
    doi = {},
}
````
4- The entries NOT processed (because they alread have the particular record) are written back AS-IS, with no reformatting.

This would help users that are trying to understand how files are processed and users who would like to compare the files before and after processing.

**Comment by kberry** [comment]
Excellent description. I had no real idea that is how it worked myself :).
We'll add the info. Thanks Paulo.

**Comment by kberry** [comment]
Hi Paulo - I tweaked the documentation in both crossrefware and bibtexperllibs with your suggestions. (I have one more feature to implement before asking Boris to make another release.) Thanks again.
