### ISSUE TITLE
Bug bbl2bib - nonreproduceable

### ISSUE THREAD

**Issue by pauloney** [borisveytsman/crossrefware#4]
Here is a bug that will probably be very hard to track -- it is non-reproducible, sometimes it shows up on a run, sometimes not. It probably has something to do either with the return from MRef or how bad the network connection is at a given time. Hopefully one will be able to track things from the error message.

When the following record is fed to bbl2bib:

    \begin{thebibliography}{00}

    \bibitem{RS}  S. Rohde, O. Schramm (2005). Basic properties of $SLE$, Annals of
    Math. {\bf 161},  883--924.
    
    \bibitem {SD}
    H. Saleur and B. Duplantier (1987).  Exact determination of the percolation hull exponent in 2d, Phys. Rev.
    Lett. {\bf 58}, 2325–-2328
    
    % \bibitem{MDM} S.S. Manna, D. Dhar, S. Majumdar (1992). Spanning
    % trees in two dimensions, Phys. Rev. A {\bf 46}, R4471(R).
    %
    %% \bibitem{Marchal} P. Marchal (2000).
    %  Loop-Erased Random Walks, Spanning Trees and Hamiltonian Cycles
    %  {\bf 5}, paper no, 4, 39--50.

    
    % \bibitem{Pemantle}  R. Pemantle (1991). Choosing a spanning tree
    % for the integer lattice uniformly, Ann. Probab. {\bf 19}, 1559--1574.
    
    % \bibitem{Cortona} M. Picadello and W. Weiss, ed., (1999).
    % {\em Random Walks and Discrete Potential Theory}, conference
    % proceedings from Cortona 1997, Cambridge U. Press.

    
    \end{thebibliography}

sometime it comes back with the error:

    Can't locate object method "editors" via package "BibTeX::Parser::Entry" at /usr/local/texlive/2016/texmf-dist/scripts/bibtexperllibs/BibTeX/Parser/Entry.pm line 237.

**Comment by borisveytsman** [comment]
Looks like a problem with mathscinet is solved.
